// Generated by CoffeeScript 1.6.3
(function() {
  var canvas, ctx, drawRobot, field, fillPattern, mkImagePattern, paint, paintField, robot;

  canvas = document.getElementById("canvas");

  field = document.getElementById("field");

  robot = document.getElementById("robot");

  ctx = canvas.getContext("2d");

  mkImagePattern = function(img) {
    return ctx.createPattern(img, 'repeat');
  };

  fillPattern = function(pattern, xi, yi, xf, yf) {
    ctx.rect(xi, yi, xf, yf);
    ctx.fillStyle = pattern;
    return ctx.fill();
  };

  paintField = function() {
    return fillPattern(mkImagePattern(field), 0, 0, canvas.width, canvas.height);
  };

  drawRobot = function(degrees) {
    var image;
    image = robot;
    ctx.save();
    ctx.translate(canvas.width / 2, canvas.height / 2);
    ctx.rotate(degrees * Math.PI / 180);
    ctx.drawImage(image, -image.width / 2, -image.width / 2);
    return ctx.restore();
  };

  window.onload = function() {
    paintField();
    return drawRobot(-22);
  };

  robot.angles = 0;

  paint = function() {
    console.log("painting");
    paintField();
    drawRobot(robot.angles);
    return robot.angles += 3;
  };

  setInterval(paint, 25);

}).call(this);
